---
- hosts: all
  handlers:
    - name: restart systemd-journald
      service:
        name: systemd-journald
        state: restarted

  tasks:
    - name: Fail if not running on Ubuntu
      fail:
        msg: This playbook only works on Ubuntu systems!
      when: ansible_distribution != 'Ubuntu'
      tags: always

    - name: Fail if Ubuntu older than 20.04
      fail:
        msg: This playbook requires Ubuntu >= 20.04
      when: ansible_distribution_major_version|int < 20
      tags: always

    - include: tasks/systemd.yml
      tags:
        - default
        - systemd

    - include: tasks/general.yml
      tags:
        - default
        - general

    - include: tasks/mysql.yml
      tags:
        - default
        - mysql

    - include: tasks/php-fpm.yml
      tags:
        - default
        - php-fpm

    - include: tasks/nginx.yml
      tags:
        - default
        - nginx

    - include: tasks/phpmyadmin.yml
      tags:
        - default
        - pma

    - include: tasks/tfs.yml
      tags:
        - default
        - tfs

    - include: tasks/tfs-old.yml
      tags:
        - tfs-old

    - include: tasks/wine.yml
      tags: wine

    - name: reload systemd
      command: /bin/systemctl daemon-reload
