---
- name: Stop php-fpm Service
  ignore_errors: yes
  service:
    name: "{{item}}"
    state: stopped
    enabled: false
  with_items:
    - php-fpm
    - php8.1-fpm
    - php7.4-fpm

- name: Delete /etc/systemd/system/php-fpm.service.d
  file:
    path: /etc/systemd/system/php-fpm.service.d
    state: absent

- name: Uninstall php-fpm
  apt:
    state: absent
    pkg:
      - php-fpm
      - php-apcu
      - php-mysqlnd
      - php-curl
      - php-xml
      - php-mbstring
      - composer

- name: Delete php folder
  file:
    path: /etc/php/
    state: absent
