---
- name: Uninstall packages needed to compile TFS
  apt:
    state: absent
    pkg:
      - git
      - cmake
      - build-essential
      - libmysqlclient-dev
      - libboost-system-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libcrypto++-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libpugixml-dev
      - libfmt-dev

- name: Uninstall systemd services for TFS
  service:
    name: {{item}}
    state: stopped
    enabled: false
  with_items:
    - tfs
    - tfs-gdb
